### ISSUE TITLE
memory leak after long time run

### ISSUE THREAD

**Issue by cocalele** [cocalele/jconductor#4]
case 1: Resident memory continue increase if you run `pfcli list_volume`.

case 2: on the test of ViveNAS, pfc may crashed with OOM.
```
[5349.352s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[5349.352s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[2023/03/23 0:14:05.362] [HttpClient@1467650828-236098] WARN org.eclipse.jetty.util.thread.QueuedThreadPool -
[2023/03/23 0:14:05.362] [HttpClient@1467650828-236097] WARN org.eclipse.jetty.util.thread.QueuedThreadPool -
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:801)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:447)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:598)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:801)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:447)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:598)
        at java.base/java.lang.Thread.run(Thread.java:832)
[2023/03/23 0:14:05.363] [HttpClient@1467650828-236097] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@6c331fa3 in HttpClient@1467650828{STARTED,8<=49<=200,i=0,q=0}
```

**Comment by cocalele** [comment]
for first case, long time run pfcli command, seems memory stop increasing at 1.4G
